### ISSUE TITLE
[host.py] AttributeError: 'DisassociationEvent' object has no attribute 'fields'

### ISSUE THREAD

**Issue by TSRBerry** [kinnay/LDN#2]
Hi,

I've been playing around with your package for a while now and with a lot of your help I was able to get a Mario Kart 8 Lobby to show up on the switch!
But a few seconds after clicking on this lobby, the script throws this exception. I don't really now your package well enough yet, to create a PR with a fix, so at least I want to let you know about this issue.

```
Creating network.
Listening for events.
Julian joined the network (00:00:00:00:00:00 / 169.254.118.2)
Traceback (most recent call last):
  File "/home/julian/Documents/LDN/examples/host.py", line 82, in <module>
    trio.run(main)
  File "/home/julian/.local/lib/python3.10/site-packages/trio/_core/_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "/home/julian/Documents/LDN/examples/host.py", line 70, in main
    async with ldn.create_network(param) as network:
  File "/usr/lib/python3.10/contextlib.py", line 217, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/julian/Documents/LDN/examples/ldn/__init__.py", line 1244, in create_network
    async with network.start():
  File "/usr/lib/python3.10/contextlib.py", line 217, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/julian/Documents/LDN/examples/ldn/__init__.py", line 1084, in start
    async with util.background_task(self.process_events):
  File "/usr/lib/python3.10/contextlib.py", line 217, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/julian/Documents/LDN/examples/ldn/util.py", line 8, in background_task
    async with trio.open_nursery() as nursery:
  File "/home/julian/.local/lib/python3.10/site-packages/trio/_core/_run.py", line 813, in __aexit__
    raise combined_error_from_nursery
  File "/home/julian/Documents/LDN/examples/ldn/__init__.py", line 1096, in process_events
    await self.process_disassociation(event)
  File "/home/julian/Documents/LDN/examples/ldn/__init__.py", line 1145, in process_disassociation
    if participant.connected and participant.mac_address == address:
  File "/home/julian/Documents/LDN/examples/ldn/wlan.py", line 121, in __eq__
    return self.fields == other.fields
AttributeError: 'DisassociationEvent' object has no attribute 'fields'
```

You can find my modified version of host.py here: [host-mk8.py](https://github.com/TSRBerry/ldn_utils/blob/78555db7846e31de8ae03db99062b8d35dc42a41/python/host-mk8.py)

**Comment by kinnay** [comment]
Thanks. See c47902ab33d7412efacb1308627ae04ab3ce6869. Can you check if it's fixed?

**Comment by TSRBerry** [comment]
yup, that did the trick! Thank you! :D
